# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22a203eb8dfc8082ef3edec05ef59a3be96cb2268ec5cae19104a13c8e517e0f02802adacf18d1d4ee2088e5c50a4fbcb1562449e24e4888b1e8219cd59753d6

test:
  secret_key_base: 720919a3ed041d76ec5041fe3699ed3433d3aeb37e34d85dba4c8bcbcb28bbf714994d6eec2501669bc09b0a6a327a0b9cf6b7d3b018bbbf2f1b96bfbc7e03ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
